repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Format
        entry: poetry run poe format
        language: system
        types: [python]
        stages: [pre-commit, pre-push]
      - id: ruff-check
        name: Ruff Check
        entry: poetry run poe check
        language: system
        types: [python]
        stages: [pre-commit, pre-push]
