name: Python CI
on:
  push:
    branches:
      - "**/main"
      - "main"
      - "**/add-your-bot-here"
      - "add-your-bot-here"
  pull_request:
    branches:
      - "**/main"
      - "main"
      - "**/add-your-bot-here"
      - "add-your-bot-here"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  # Only run the for the latest commit
  cancel-in-progress: true

env:
  POETRY_VERSION: 1.8.5

jobs:
  python-ci:
    # skip draft PRs
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
      fail-fast: false # Continue running all jobs even if one fails
    env:
      DEBUG: 1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: $POETRY_VERSION

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Check
        run: |
          poetry run poe check

      - name: Build
        run: |
          poetry build

      - name: Test
        run: |
          poetry run poe test
